// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7eN8PCHM4od5h5t90KLsRPz06pEp0BUE',
    appId: '1:666941021435:web:01458afe5964e5d620e45e',
    messagingSenderId: '666941021435',
    projectId: 'greenthumb-d26be',
    authDomain: 'greenthumb-d26be.firebaseapp.com',
    storageBucket: 'greenthumb-d26be.appspot.com',
    measurementId: 'G-EC59CYB614',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8p_maHfcR9iQm_ot6knlD8KA6g9VgcGs',
    appId: '1:666941021435:android:bbaef93d7a8df43d20e45e',
    messagingSenderId: '666941021435',
    projectId: 'greenthumb-d26be',
    storageBucket: 'greenthumb-d26be.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7eN8PCHM4od5h5t90KLsRPz06pEp0BUE',
    appId: '1:666941021435:web:6e8fe6d1d7acde2520e45e',
    messagingSenderId: '666941021435',
    projectId: 'greenthumb-d26be',
    authDomain: 'greenthumb-d26be.firebaseapp.com',
    storageBucket: 'greenthumb-d26be.appspot.com',
    measurementId: 'G-K0E0WVEY00',
  );
}
